version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    entrypoint:  dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh
    command: sh -c "npm install && node index.js"
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db


  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 10
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    networks: 
      - node-network
    depends_on:
      - app
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "8080:80"

    

networks: 
  node-network:
    driver: bridge      
